apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SelectNode
metadata:
  name: select-node
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["project-1"]