apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SelectNode2
metadata:
  name: select-node
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector: role=master